[2022-07-04 20:24:29,636] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-07-04T20:23:58.991922+00:00 [queued]>
[2022-07-04 20:24:29,805] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-07-04T20:23:58.991922+00:00 [queued]>
[2022-07-04 20:24:29,805] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 20:24:29,810] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-04 20:24:29,810] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 20:24:30,042] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_in_xlsx> on 2022-07-04 20:23:58.991922+00:00
[2022-07-04 20:24:30,090] {standard_task_runner.py:52} INFO - Started process 286 to run task
[2022-07-04 20:24:30,166] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'convert_xls_in_xlsx', 'manual__2022-07-04T20:23:58.991922+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpg02fto6q', '--error-file', '/tmp/tmplybnco8z']
[2022-07-04 20:24:30,168] {standard_task_runner.py:80} INFO - Job 23: Subtask convert_xls_in_xlsx
[2022-07-04 20:24:30,532] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx manual__2022-07-04T20:23:58.991922+00:00 [running]> on host cb2d0d9ed0ca
[2022-07-04 20:24:31,066] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_in_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T20:23:58.991922+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T20:23:58.991922+00:00
[2022-07-04 20:25:11,282] {python.py:173} INFO - Done. Returned value was: None
[2022-07-04 20:25:11,579] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=convert_xls_in_xlsx, execution_date=20220704T202358, start_date=20220704T202429, end_date=20220704T202511
[2022-07-04 20:25:11,717] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-04 20:25:11,913] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
