[2022-07-05 14:56:21,335] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_ANP_Raízen.xls_to_xlsx manual__2022-07-05T14:56:02.447491+00:00 [queued]>
[2022-07-05 14:56:21,559] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_ANP_Raízen.xls_to_xlsx manual__2022-07-05T14:56:02.447491+00:00 [queued]>
[2022-07-05 14:56:21,559] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 14:56:21,559] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-05 14:56:21,560] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 14:56:21,901] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): xls_to_xlsx> on 2022-07-05 14:56:02.447491+00:00
[2022-07-05 14:56:21,950] {standard_task_runner.py:52} INFO - Started process 529 to run task
[2022-07-05 14:56:21,993] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_ANP_Raízen', 'xls_to_xlsx', 'manual__2022-07-05T14:56:02.447491+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpnrvlqkzb', '--error-file', '/tmp/tmp_ggo8mvq']
[2022-07-05 14:56:22,005] {standard_task_runner.py:80} INFO - Job 70: Subtask xls_to_xlsx
[2022-07-05 14:56:22,757] {task_command.py:369} INFO - Running <TaskInstance: ETL_ANP_Raízen.xls_to_xlsx manual__2022-07-05T14:56:02.447491+00:00 [running]> on host e795889a6d4b
[2022-07-05 14:56:23,472] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_ANP_Raízen
AIRFLOW_CTX_TASK_ID=xls_to_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T14:56:02.447491+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-05T14:56:02.447491+00:00
[2022-07-05 14:56:44,560] {python.py:173} INFO - Done. Returned value was: None
[2022-07-05 14:56:44,601] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_ANP_Raízen, task_id=xls_to_xlsx, execution_date=20220705T145602, start_date=20220705T145621, end_date=20220705T145644
[2022-07-05 14:56:44,674] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-05 14:56:44,784] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
