[2022-07-04 20:30:32,974] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx scheduled__2022-07-04T19:30:00+00:00 [queued]>
[2022-07-04 20:30:33,112] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx scheduled__2022-07-04T19:30:00+00:00 [queued]>
[2022-07-04 20:30:33,112] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 20:30:33,120] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-04 20:30:33,120] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 20:30:33,338] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_in_xlsx> on 2022-07-04 19:30:00+00:00
[2022-07-04 20:30:33,368] {standard_task_runner.py:52} INFO - Started process 575 to run task
[2022-07-04 20:30:33,409] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'convert_xls_in_xlsx', 'scheduled__2022-07-04T19:30:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpbfj1zmp2', '--error-file', '/tmp/tmp60p3vs7e']
[2022-07-04 20:30:33,423] {standard_task_runner.py:80} INFO - Job 26: Subtask convert_xls_in_xlsx
[2022-07-04 20:30:34,089] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx scheduled__2022-07-04T19:30:00+00:00 [running]> on host cb2d0d9ed0ca
[2022-07-04 20:30:35,297] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_in_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T19:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T19:30:00+00:00
[2022-07-04 20:31:44,311] {python.py:173} INFO - Done. Returned value was: None
[2022-07-04 20:31:44,813] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=convert_xls_in_xlsx, execution_date=20220704T193000, start_date=20220704T203032, end_date=20220704T203144
[2022-07-04 20:31:45,170] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-04 20:31:45,867] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
