[2022-07-04 23:09:02,956] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.get_file scheduled__2022-07-04T20:30:00+00:00 [queued]>
[2022-07-04 23:09:03,009] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.get_file scheduled__2022-07-04T20:30:00+00:00 [queued]>
[2022-07-04 23:09:03,009] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 23:09:03,009] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-04 23:09:03,009] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 23:09:03,111] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_file> on 2022-07-04 20:30:00+00:00
[2022-07-04 23:09:03,128] {standard_task_runner.py:52} INFO - Started process 123 to run task
[2022-07-04 23:09:03,155] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'get_file', 'scheduled__2022-07-04T20:30:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpatb_jtq6', '--error-file', '/tmp/tmpgz406fao']
[2022-07-04 23:09:03,158] {standard_task_runner.py:80} INFO - Job 40: Subtask get_file
[2022-07-04 23:09:03,327] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.get_file scheduled__2022-07-04T20:30:00+00:00 [running]> on host d342cad78eb0
[2022-07-04 23:09:03,589] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=get_file
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T20:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T20:30:00+00:00
[2022-07-04 23:09:06,773] {python.py:173} INFO - Done. Returned value was: None
[2022-07-04 23:09:07,123] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=get_file, execution_date=20220704T203000, start_date=20220704T230902, end_date=20220704T230907
[2022-07-04 23:09:07,186] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-04 23:09:07,264] {dagrun.py:648} WARNING - Failed to get task '<TaskInstance: Teste_ETL_Raízen.transform_n_load_datas scheduled__2022-07-04T20:30:00+00:00 [removed]>' for dag 'Teste_ETL_Raízen'. Marking it as removed.
[2022-07-04 23:09:07,266] {dagrun.py:648} WARNING - Failed to get task '<TaskInstance: Teste_ETL_Raízen.download_file_xls scheduled__2022-07-04T20:30:00+00:00 [removed]>' for dag 'Teste_ETL_Raízen'. Marking it as removed.
[2022-07-04 23:09:07,267] {dagrun.py:648} WARNING - Failed to get task '<TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx scheduled__2022-07-04T20:30:00+00:00 [removed]>' for dag 'Teste_ETL_Raízen'. Marking it as removed.
[2022-07-04 23:09:07,298] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
